### ISSUE TITLE
Unknown UBJSON fields should be ignored when unmarshalling

### ISSUE THREAD

**Issue by peergynt** [jmank88/ubjson#9]
@jmank88 I was wondering what your thoughts were on fields that are in the UBJSON object but not declared in the Go struct.
Currently, I see the error: `unable to decode entry: no field found named/tagged ...`
When I do the same test using encoding/json, the 'unknown' JSON field is consumed and discarded.

A use case is to implement forward compatibility with UBJSON messages.
I can add a failing test if you'd like.

**Comment by jmank88** [comment]
This seems fine to me.  I can't find any historical reason or think of any other reasons to force the error, and  if someone finds it useful later on it could always be optional via some sort of decoder `strict mode` flag or similar.  Don't worry about the test, I'll put up a PR shortly.
